// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include <stdint.h> /* for uint8_t */

extern uint8_t ui_time_hour;
extern uint8_t ui_time_minute;
bool ui_is_booking_active(void);
int ui_get_booking_remaining_sec_snapshot(void);
void ui_start_meeting_duration(int seconds);
void ui_stop_meeting_now(void);

void ui_set_time(uint8_t hour, uint8_t minute);
void ui_time_init(void);

extern lv_obj_t *ui_RollerHour;
extern lv_obj_t *ui_RollerMinute;

///////////////////// SCREENS ////////////////////
#include "ui_Screen8.h"
#include "ui_Screen1.h"
#include "ui_ScreenInfo.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1474184779);
LV_IMG_DECLARE( ui_img_630012529);
LV_IMG_DECLARE( ui_img_infoicon_png);
LV_IMG_DECLARE(ui_img_wifi32_png);
LV_IMG_DECLARE(ui_img_settingsbuttonan_png);
LV_IMG_DECLARE(ui_img_653468872);
LV_IMG_DECLARE(ui_img_wifiicon13_png);
LV_IMG_DECLARE(ui_img_smartphone_png);
LV_IMG_DECLARE(ui_img_nameicon_png);
LV_IMG_DECLARE(ui_img_moonicon_png);

LV_FONT_DECLARE(ui_font_Roboto16);
LV_FONT_DECLARE(ui_font_Roboto18);
LV_FONT_DECLARE(ui_font_Roboto26);
LV_FONT_DECLARE(ui_font_Roboto30);
LV_FONT_DECLARE(ui_font_Roboto34);
LV_FONT_DECLARE(ui_font_Roboto50);
LV_FONT_DECLARE(ui_font_Roboto20);
LV_FONT_DECLARE(ui_font_Roboto12);
LV_FONT_DECLARE(ui_font_Roboto14);
LV_FONT_DECLARE(ui_font_Roboto40);
LV_FONT_DECLARE(ui_font_Roboto55);
LV_FONT_DECLARE(ui_font_Roboto60);

LV_FONT_DECLARE(ui_font_FontZh12);
LV_FONT_DECLARE(ui_font_FontZh14);
LV_FONT_DECLARE(ui_font_FontZh16);
LV_FONT_DECLARE(ui_font_Fonttt16);
LV_FONT_DECLARE(ui_font_FontZh18);
LV_FONT_DECLARE(ui_font_FontZh20);
LV_FONT_DECLARE(ui_font_FontZh26);
LV_FONT_DECLARE(ui_font_FontZh30);
LV_FONT_DECLARE(ui_font_FontZhh50);

/* Route text fonts used by the static UI to the Chinese-capable subset fonts.
 * Large numeric-only fonts stay on the original assets. */
#define ui_font_Roboto12 ui_font_FontZh12
#define ui_font_Roboto14 ui_font_FontZh14
#define ui_font_Roboto16 ui_font_FontZh16
#define ui_font_Roboto18 ui_font_FontZh18
#define ui_font_Roboto20 ui_font_FontZh20
#define ui_font_Roboto26 ui_font_FontZh26
#define ui_font_Roboto30 ui_font_FontZh30



// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_update_time_display(uint8_t hour, uint8_t minute);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
