// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENINFO_H
#define UI_SCREENINFO_H

#ifdef __cplusplus
extern "C" {
#endif
#include "lvgl.h"

// SCREEN: ui_ScreenInfo
extern void ui_ScreenInfo_screen_init(void);
extern void ui_ScreenInfo_screen_destroy(void);
extern lv_obj_t *ui_ScreenInfo;
extern lv_obj_t *ui_HeaderInfo;
extern lv_obj_t *ui_InfoLabelHeader;
extern lv_obj_t *ui_BodyInfo;
extern lv_obj_t *ui_LeftBody;
extern lv_obj_t *ui_GuestWifi;
extern lv_obj_t *ui_GuestCont;
extern lv_obj_t *ui_HeaderGuest;
extern lv_obj_t *ui_HeaderGuestLabel1;
extern lv_obj_t *ui_HeaderGuestLabel2;
extern lv_obj_t *ui_BottomHeader;
extern lv_obj_t *ui_BottonWifi;
extern lv_obj_t *ui_BottomPass;
extern lv_obj_t *ui_GuestImage;
extern lv_obj_t *ui_CompanyWeb;
extern lv_obj_t *ui_CompanyCont;
extern lv_obj_t *ui_HeaderComp;
extern lv_obj_t *ui_ComanyHeaderLabel1;
extern lv_obj_t *ui_CompanyHeaderLabel2;
extern lv_obj_t *ui_BottomComp;
extern lv_obj_t *ui_ScanComp;
extern lv_obj_t *ui_CompanyImage;
extern lv_obj_t *ui_ExitButtonInfo;
extern lv_obj_t *ui_ExitButtonLabel;
extern lv_obj_t *ui_RightBody;
extern lv_obj_t *ui_OfficePanel;
extern lv_obj_t *ui_OfficeCont;
extern lv_obj_t *ui_HeaderOffice;
extern lv_obj_t *ui_HeaderOfficeLabel1;
extern lv_obj_t *ui_HeaderOfficeLanel2;
extern lv_obj_t *ui_BottonOffice;
extern lv_obj_t *ui_ScanOffice;
extern lv_obj_t *ui_OfficeImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
