// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN8_H
#define UI_SCREEN8_H
#include <stdbool.h>
#ifdef __cplusplus
extern "C" {
#endif
#include "lvgl.h"
// SCREEN: ui_Screen8
extern void ui_Screen8_screen_init(void);
extern void ui_Screen8_screen_destroy(void);
extern lv_obj_t *ui_Screen8;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_Container26;
extern lv_obj_t *ui_Label41;
extern lv_obj_t *ui_Label42;
extern lv_obj_t *ui_Container27;
extern lv_obj_t *ui_Label43;
extern lv_obj_t *ui_Container25;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Container28;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label47;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label48;
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label49;
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label50;
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label51;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Label39;
extern lv_obj_t *ui_Container3;
extern void ui_event_Panel2( lv_event_t * e);
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Image12;
extern lv_obj_t *ui_Label38;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_ImgBtn;
extern lv_obj_t *ui_ImgBtnImg;

/* wifi indicator shown in top‑right when the board is connected */
extern lv_obj_t *ui_WifiIcon;

/* helper for other modules to refresh the header icon (eg. after a WiFi event) */
void ui_Screen8_update_wifi_icon(void);
void ui_Screen8_refresh_device_name(void);
int ui_get_booking_remaining_sec_snapshot(void);

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
