// This file was generated by SquareLine Studio (modified by assistant)
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "language_manager.h" /* NEW: language support */
#include "info_links_store.h"
#include "wifi_manager.h"

#include <stdio.h>
#include <string.h>

bool lvgl_port_lock(int timeout_ms);
bool lvgl_port_unlock(void);

lv_obj_t *ui_ScreenInfo = NULL;
lv_obj_t *ui_HeaderInfo = NULL;
lv_obj_t *ui_InfoLabelHeader = NULL;
lv_obj_t *ui_BodyInfo = NULL;
lv_obj_t *ui_LeftBody = NULL;
lv_obj_t *ui_GuestWifi = NULL;
lv_obj_t *ui_GuestCont = NULL;
lv_obj_t *ui_HeaderGuest = NULL;
lv_obj_t *ui_HeaderGuestLabel1 = NULL;
lv_obj_t *ui_HeaderGuestLabel2 = NULL;
lv_obj_t *ui_BottomHeader = NULL;
lv_obj_t *ui_BottonWifi = NULL;
lv_obj_t *ui_BottomPass = NULL;
lv_obj_t *ui_GuestImage = NULL;
lv_obj_t *ui_CompanyWeb = NULL;
lv_obj_t *ui_CompanyCont = NULL;
lv_obj_t *ui_HeaderComp = NULL;
lv_obj_t *ui_ComanyHeaderLabel1 = NULL;
lv_obj_t *ui_CompanyHeaderLabel2 = NULL;
lv_obj_t *ui_BottomComp = NULL;
lv_obj_t *ui_ScanComp = NULL;
lv_obj_t *ui_CompanyImage = NULL;
lv_obj_t *ui_ExitButtonInfo = NULL;
lv_obj_t *ui_ExitButtonLabel = NULL;
lv_obj_t *ui_RightBody = NULL;
lv_obj_t *ui_OfficePanel = NULL;
lv_obj_t *ui_OfficeCont = NULL;
lv_obj_t *ui_HeaderOffice = NULL;
lv_obj_t *ui_HeaderOfficeLabel1 = NULL;
lv_obj_t *ui_HeaderOfficeLanel2 = NULL;
lv_obj_t *ui_BottonOffice = NULL;
lv_obj_t *ui_ScanOffice = NULL;
lv_obj_t *ui_OfficeImage = NULL;

/* language callback id for unsubscribe */
static int s_lang_cb_id = -1;
static const lv_coord_t UI_INFO_TEXT_COLUMN_WIDTH = 176;
static const lv_coord_t UI_INFO_TEXT_COLUMN_OFFSET_X = -84;
static const lv_coord_t UI_INFO_QR_OFFSET_X = 96;

static void ui_info_refresh_dynamic_content(void);
static void ui_info_style_qr_frame(lv_obj_t *frame);
static void ui_info_update_qr_frame(lv_obj_t *frame, const char *payload, const char *fallback_text);
static void ui_info_escape_wifi_qr_text(const char *src, char *dst, size_t dst_size);
static void ui_info_set_key_value_label(lv_obj_t *label, const char *key, const char *value);
static void ui_info_refresh_guest_wifi_card(bool en);
static void ui_info_refresh_company_website_card(bool en);
static void ui_info_refresh_office_map_card(bool en);

static void ui_info_style_qr_frame(lv_obj_t *frame)
{
    if (!frame) {
        return;
    }

    lv_obj_set_size(frame, 130, 130);
    lv_obj_set_style_radius(frame, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(frame, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(frame, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(frame, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(frame, lv_color_hex(0x5BA6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(frame, LV_OPA_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(frame, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(frame, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(frame, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(frame, LV_OBJ_FLAG_ADV_HITTEST);
}

static void ui_info_update_qr_frame(lv_obj_t *frame, const char *payload, const char *fallback_text)
{
    if (!frame) {
        return;
    }

    lv_obj_clean(frame);

#if LV_USE_QRCODE
    if (payload && payload[0] != '\0') {
        lv_obj_t *qr = lv_qrcode_create(frame, 110, lv_color_hex(0x0B1220), lv_color_hex(0xFFFFFF));
        if (lv_qrcode_update(qr, payload, strlen(payload)) == LV_RES_OK) {
            lv_obj_center(qr);
            return;
        }
        lv_obj_del(qr);
    }
#endif

    lv_obj_t *label = lv_label_create(frame);
    lv_label_set_text(label, fallback_text ? fallback_text : "QR unavailable");
    lv_obj_set_width(label, lv_pct(100));
    lv_label_set_long_mode(label, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_color(label, lv_color_hex(0x1D2939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, &ui_font_Roboto14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(label);
}

static void ui_info_escape_wifi_qr_text(const char *src, char *dst, size_t dst_size)
{
    if (!dst || dst_size == 0) {
        return;
    }

    dst[0] = '\0';
    if (!src) {
        return;
    }

    size_t out = 0;
    for (size_t i = 0; src[i] != '\0' && out + 1 < dst_size; ++i) {
        if (src[i] == '\\' || src[i] == ';' || src[i] == ',' || src[i] == ':') {
            if (out + 2 >= dst_size) {
                break;
            }
            dst[out++] = '\\';
        }
        dst[out++] = src[i];
    }
    dst[out] = '\0';
}

static void ui_info_set_key_value_label(lv_obj_t *label, const char *key, const char *value)
{
    if (!label || !key) {
        return;
    }

    const char *safe_value = value ? value : "-";
    char buffer[160];
    snprintf(buffer, sizeof(buffer), "%s %s", key, safe_value);
    buffer[sizeof(buffer) - 1] = '\0';

    lv_label_set_long_mode(label, LV_LABEL_LONG_DOT);
    lv_label_set_text(label, buffer);
}

static void ui_info_refresh_guest_wifi_card(bool en)
{
    char ssid[33] = {0};
    char pass[65] = {0};
    char ssid_escaped[70] = {0};
    char pass_escaped[140] = {0};
    char qr_payload[256] = {0};

    esp_err_t err = wifi_manager_fetch_credentials(ssid, pass);
    bool has_credentials = (err == ESP_OK && ssid[0] != '\0');
    const char *open_text = en ? "Open network" : "开放网络";

    if (has_credentials) {
        ui_info_escape_wifi_qr_text(ssid, ssid_escaped, sizeof(ssid_escaped));
        ui_info_escape_wifi_qr_text(pass, pass_escaped, sizeof(pass_escaped));

        if (pass[0] != '\0') {
            snprintf(qr_payload, sizeof(qr_payload), "WIFI:T:WPA;S:%s;P:%s;;", ssid_escaped, pass_escaped);
        } else {
            snprintf(qr_payload, sizeof(qr_payload), "WIFI:T:nopass;S:%s;;", ssid_escaped);
        }

        if (ui_BottonWifi) {
            ui_info_set_key_value_label(ui_BottonWifi, en ? "Wi-Fi:" : "Wi-Fi:", ssid);
        }
        if (ui_BottomPass) {
            ui_info_set_key_value_label(ui_BottomPass, en ? "Password:" : "密码:", pass[0] ? pass : open_text);
        }
        ui_info_update_qr_frame(ui_GuestImage, qr_payload, en ? "QR unavailable" : "二维码暂不可用");
        return;
    }

    if (ui_BottonWifi) {
        ui_info_set_key_value_label(ui_BottonWifi, en ? "Wi-Fi:" : "Wi-Fi:", en ? "not configured" : "未配置");
    }
    if (ui_BottomPass) {
        ui_info_set_key_value_label(ui_BottomPass, en ? "Password:" : "密码:", "-");
    }
    ui_info_update_qr_frame(ui_GuestImage, NULL, en ? "Wi-Fi unavailable" : "Wi-Fi暂不可用");
}

static void ui_info_refresh_company_website_card(bool en)
{
    char company_website_url[INFO_LINKS_STORE_MAX_URL_LEN + 1] = {0};

    info_links_store_get_company_website_copy(company_website_url, sizeof(company_website_url));
    ui_info_update_qr_frame(
        ui_CompanyImage,
        company_website_url[0] ? company_website_url : NULL,
        en ? "Link not set" : "链接未设置");
}

static void ui_info_refresh_office_map_card(bool en)
{
    char office_map_url[INFO_LINKS_STORE_MAX_URL_LEN + 1] = {0};

    info_links_store_get_office_map_copy(office_map_url, sizeof(office_map_url));
    ui_info_update_qr_frame(
        ui_OfficeImage,
        office_map_url[0] ? office_map_url : NULL,
        en ? "Link not set" : "链接未设置");
}

static void ui_info_refresh_dynamic_content(void)
{
    bool en = language_get_en();
    ui_info_refresh_guest_wifi_card(en);
    ui_info_refresh_company_website_card(en);
    ui_info_refresh_office_map_card(en);
}

/* event funtions */
void ui_event_ExitButtonInfo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED) {
        _ui_screen_change( &ui_Screen8, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen8_screen_init);
    }
}

/* ----------------------------
   language apply helper
   ---------------------------- */
static void ui_info_apply_language(bool en)
{
    /* Header */
    if (ui_InfoLabelHeader) {
        lv_label_set_text(ui_InfoLabelHeader, en ? "Info" : "信息");
    }

    /* Guest Wi-Fi section */
    if (ui_HeaderGuestLabel1) {
        lv_label_set_text(ui_HeaderGuestLabel1, en ? "Guest Wi-Fi" : "访客Wi-Fi");
    }
    if (ui_HeaderGuestLabel2) {
        lv_label_set_text(ui_HeaderGuestLabel2, "");
        lv_obj_add_flag(ui_HeaderGuestLabel2, LV_OBJ_FLAG_HIDDEN);
    }

    /* Company Web section */
    if (ui_ComanyHeaderLabel1) {
        lv_label_set_text(ui_ComanyHeaderLabel1, en ? "Company Website" : "公司网站");
    }
    if (ui_CompanyHeaderLabel2) {
        lv_label_set_text(ui_CompanyHeaderLabel2, "");
        lv_obj_add_flag(ui_CompanyHeaderLabel2, LV_OBJ_FLAG_HIDDEN);
    }
    if (ui_ScanComp) {
        lv_label_set_text(ui_ScanComp, en ? "Scan QR\nfor website" : "扫二维码\n查看网站");
    }

    /* Office section */
    if (ui_HeaderOfficeLabel1) {
        lv_label_set_text(ui_HeaderOfficeLabel1, en ? "Office Map" : "平面图");
    }
    if (ui_HeaderOfficeLanel2) {
        lv_label_set_text(ui_HeaderOfficeLanel2, "");
        lv_obj_add_flag(ui_HeaderOfficeLanel2, LV_OBJ_FLAG_HIDDEN);
    }
    if (ui_ScanOffice) {
        lv_label_set_text(ui_ScanOffice, en ? "Scan QR\nfor office map" : "扫二维码\n查看平面图");
    }

    /* Exit button label — keep arrow but could be text */
    if (ui_ExitButtonLabel) {
        /* Keep as arrow; replace with "Back"/"Zurück" if needed */
        lv_label_set_text(ui_ExitButtonLabel, "<");
    }

    ui_info_refresh_dynamic_content();
}

/* language manager callback for this screen */
static void ui_info_lang_cb(bool en, void *ctx)
{
    (void)ctx;
    ui_info_apply_language(en);
}

/* build funtions */
void ui_ScreenInfo_screen_init(void)
{
    ui_ScreenInfo = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_ScreenInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_flex_flow(ui_ScreenInfo,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenInfo, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ScreenInfo, lv_color_hex(0x12100F), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_ScreenInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ScreenInfo, 50, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_HeaderInfo = lv_obj_create(ui_ScreenInfo);
    lv_obj_remove_style_all(ui_HeaderInfo);
    lv_obj_set_width( ui_HeaderInfo, 800);
    lv_obj_set_height( ui_HeaderInfo, 49);
    lv_obj_set_align( ui_HeaderInfo, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_HeaderInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_InfoLabelHeader = lv_label_create(ui_HeaderInfo);
    lv_obj_set_width( ui_InfoLabelHeader, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_InfoLabelHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_InfoLabelHeader, LV_ALIGN_CENTER );
    /* initial text (will be overridden by language apply) */
    lv_label_set_text(ui_InfoLabelHeader,"Info");
    lv_obj_set_style_text_color(ui_InfoLabelHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_InfoLabelHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InfoLabelHeader, &ui_font_Roboto30, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_BodyInfo = lv_obj_create(ui_ScreenInfo);
    lv_obj_remove_style_all(ui_BodyInfo);
    lv_obj_set_width( ui_BodyInfo, 800);
    lv_obj_set_height( ui_BodyInfo, 410);
    lv_obj_set_align( ui_BodyInfo, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_BodyInfo,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BodyInfo, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag( ui_BodyInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_pad_left(ui_BodyInfo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BodyInfo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BodyInfo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BodyInfo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BodyInfo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BodyInfo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_LeftBody = lv_obj_create(ui_BodyInfo);
    lv_obj_remove_style_all(ui_LeftBody);
    lv_obj_set_width( ui_LeftBody, 370);
    lv_obj_set_height( ui_LeftBody, lv_pct(97));
    lv_obj_set_x( ui_LeftBody, -1 );
    lv_obj_set_y( ui_LeftBody, -1 );
    lv_obj_set_align( ui_LeftBody, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_LeftBody,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_LeftBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_LeftBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_pad_row(ui_LeftBody, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_LeftBody, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_GuestWifi = lv_obj_create(ui_LeftBody);
    lv_obj_set_width( ui_GuestWifi, lv_pct(95));
    lv_obj_set_height( ui_GuestWifi, lv_pct(40));
    lv_obj_set_align( ui_GuestWifi, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_GuestWifi,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_GuestWifi, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_GuestWifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_radius(ui_GuestWifi, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GuestWifi, lv_color_hex(0x303031), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_GuestWifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GuestWifi, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_border_opa(ui_GuestWifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GuestWifi, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_GuestWifi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_GuestWifi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_GuestWifi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_GuestWifi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_GuestWifi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_GuestWifi, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_GuestCont = lv_obj_create(ui_GuestWifi);
    lv_obj_remove_style_all(ui_GuestCont);
    lv_obj_set_width( ui_GuestCont, UI_INFO_TEXT_COLUMN_WIDTH);
    lv_obj_set_height( ui_GuestCont, lv_pct(100));
    lv_obj_set_x( ui_GuestCont, UI_INFO_TEXT_COLUMN_OFFSET_X );
    lv_obj_set_y( ui_GuestCont, 0 );
    lv_obj_set_align( ui_GuestCont, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_GuestCont,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_GuestCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag( ui_GuestCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_HeaderGuest = lv_obj_create(ui_GuestCont);
    lv_obj_remove_style_all(ui_HeaderGuest);
    lv_obj_set_width( ui_HeaderGuest, lv_pct(100));
    lv_obj_set_height( ui_HeaderGuest, lv_pct(30));
    lv_obj_set_align( ui_HeaderGuest, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_HeaderGuest,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HeaderGuest, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag( ui_HeaderGuest, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_pad_row(ui_HeaderGuest, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_HeaderGuest, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_HeaderGuestLabel1 = lv_label_create(ui_HeaderGuest);
    lv_obj_set_width( ui_HeaderGuestLabel1, lv_pct(100));
    lv_obj_set_height( ui_HeaderGuestLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_HeaderGuestLabel1, LV_ALIGN_CENTER );
    lv_label_set_long_mode(ui_HeaderGuestLabel1, LV_LABEL_LONG_WRAP);
    lv_label_set_text(ui_HeaderGuestLabel1,"Guest Wi-Fi");
    lv_obj_set_style_text_color(ui_HeaderGuestLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_HeaderGuestLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaderGuestLabel1, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HeaderGuestLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaderGuestLabel2 = lv_label_create(ui_HeaderGuest);
    lv_obj_set_width( ui_HeaderGuestLabel2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_HeaderGuestLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_HeaderGuestLabel2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_HeaderGuestLabel2, language_get_en() ? "Connect to our guest network." : "连接到我们的访客网络");
    lv_obj_set_style_text_color(ui_HeaderGuestLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_HeaderGuestLabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaderGuestLabel2, &ui_font_Roboto12, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_HeaderGuestLabel2, LV_OBJ_FLAG_HIDDEN);

    ui_BottomHeader = lv_obj_create(ui_GuestCont);
    lv_obj_remove_style_all(ui_BottomHeader);
    lv_obj_set_width( ui_BottomHeader, lv_pct(100));
    lv_obj_set_height( ui_BottomHeader, lv_pct(52));
    lv_obj_set_align( ui_BottomHeader, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_BottomHeader,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BottomHeader, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_BottomHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_pad_top(ui_BottomHeader, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BottomHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BottomHeader, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_BottonWifi = lv_label_create(ui_BottomHeader);
    lv_obj_set_width( ui_BottonWifi, lv_pct(100));
    lv_obj_set_height( ui_BottonWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_BottonWifi, LV_ALIGN_CENTER );
    lv_label_set_long_mode(ui_BottonWifi, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_BottonWifi,"Wi-Fi:\nGuest_Network");
    lv_obj_set_style_text_color(ui_BottonWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_BottonWifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottonWifi, &ui_font_Roboto18, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BottonWifi, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomPass = lv_label_create(ui_BottomHeader);
    lv_obj_set_width( ui_BottomPass, lv_pct(100));
    lv_obj_set_height( ui_BottomPass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_BottomPass, LV_ALIGN_CENTER );
    lv_label_set_long_mode(ui_BottomPass, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_BottomPass,"Password: 1234");
    lv_obj_set_style_text_color(ui_BottomPass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_BottomPass, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BottomPass, &ui_font_Roboto18, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BottomPass, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GuestImage = lv_obj_create(ui_GuestWifi);
    lv_obj_set_x( ui_GuestImage, UI_INFO_QR_OFFSET_X );
    lv_obj_set_y( ui_GuestImage, 0 );
    lv_obj_set_align( ui_GuestImage, LV_ALIGN_CENTER );
    ui_info_style_qr_frame(ui_GuestImage);

    ui_CompanyWeb = lv_obj_create(ui_LeftBody);
    lv_obj_set_width( ui_CompanyWeb, lv_pct(95));
    lv_obj_set_height( ui_CompanyWeb, lv_pct(40));
    lv_obj_set_align( ui_CompanyWeb, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_CompanyWeb,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CompanyWeb, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_CompanyWeb, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_radius(ui_CompanyWeb, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CompanyWeb, lv_color_hex(0x303031), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_CompanyWeb, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CompanyWeb, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_border_opa(ui_CompanyWeb, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CompanyWeb, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CompanyWeb, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CompanyWeb, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CompanyWeb, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CompanyWeb, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_CompanyWeb, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CompanyWeb, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_CompanyCont = lv_obj_create(ui_CompanyWeb);
    lv_obj_remove_style_all(ui_CompanyCont);
    lv_obj_set_width( ui_CompanyCont, UI_INFO_TEXT_COLUMN_WIDTH);
    lv_obj_set_height( ui_CompanyCont, lv_pct(100));
    lv_obj_set_x( ui_CompanyCont, UI_INFO_TEXT_COLUMN_OFFSET_X );
    lv_obj_set_y( ui_CompanyCont, 0 );
    lv_obj_set_align( ui_CompanyCont, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_CompanyCont,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CompanyCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag( ui_CompanyCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_HeaderComp = lv_obj_create(ui_CompanyCont);
    lv_obj_remove_style_all(ui_HeaderComp);
    lv_obj_set_width( ui_HeaderComp, lv_pct(100));
    lv_obj_set_height( ui_HeaderComp, lv_pct(42));
    lv_obj_set_align( ui_HeaderComp, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_HeaderComp,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HeaderComp, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag( ui_HeaderComp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_pad_row(ui_HeaderComp, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_HeaderComp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_ComanyHeaderLabel1 = lv_label_create(ui_HeaderComp);
    lv_obj_set_width( ui_ComanyHeaderLabel1, lv_pct(100));
    lv_obj_set_height( ui_ComanyHeaderLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_ComanyHeaderLabel1, LV_ALIGN_CENTER );
    lv_label_set_long_mode(ui_ComanyHeaderLabel1, LV_LABEL_LONG_WRAP);
    lv_label_set_text(ui_ComanyHeaderLabel1,"Company Website");
    lv_obj_set_style_text_color(ui_ComanyHeaderLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_ComanyHeaderLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ComanyHeaderLabel1, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ComanyHeaderLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompanyHeaderLabel2 = lv_label_create(ui_HeaderComp);
    lv_obj_set_width( ui_CompanyHeaderLabel2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_CompanyHeaderLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_CompanyHeaderLabel2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_CompanyHeaderLabel2,"");
    lv_obj_set_style_text_color(ui_CompanyHeaderLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_CompanyHeaderLabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CompanyHeaderLabel2, &ui_font_Roboto12, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_CompanyHeaderLabel2, LV_OBJ_FLAG_HIDDEN);

    ui_BottomComp = lv_obj_create(ui_CompanyCont);
    lv_obj_remove_style_all(ui_BottomComp);
    lv_obj_set_width( ui_BottomComp, lv_pct(100));
    lv_obj_set_height( ui_BottomComp, lv_pct(34));
    lv_obj_set_align( ui_BottomComp, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_BottomComp,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BottomComp, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_BottomComp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_pad_row(ui_BottomComp, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_ScanComp = lv_label_create(ui_BottomComp);
    lv_obj_set_width( ui_ScanComp, lv_pct(100));
    lv_obj_set_height( ui_ScanComp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_ScanComp, LV_ALIGN_CENTER );
    lv_label_set_long_mode(ui_ScanComp, LV_LABEL_LONG_WRAP);
    lv_label_set_text(ui_ScanComp,"Scan QR\nfor website");
    lv_obj_set_style_text_color(ui_ScanComp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_ScanComp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScanComp, &ui_font_Roboto18, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScanComp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompanyImage = lv_obj_create(ui_CompanyWeb);
    lv_obj_set_x( ui_CompanyImage, UI_INFO_QR_OFFSET_X );
    lv_obj_set_y( ui_CompanyImage, 0 );
    lv_obj_set_align( ui_CompanyImage, LV_ALIGN_CENTER );
    ui_info_style_qr_frame(ui_CompanyImage);

    ui_ExitButtonInfo = lv_btn_create(ui_LeftBody);
    lv_obj_set_width( ui_ExitButtonInfo, 180);
    lv_obj_set_height( ui_ExitButtonInfo, 45);
    lv_obj_set_align( ui_ExitButtonInfo, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_ExitButtonInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
    lv_obj_clear_flag( ui_ExitButtonInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_radius(ui_ExitButtonInfo, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExitButtonInfo, lv_color_hex(0x303031), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_ExitButtonInfo, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ExitButtonInfo, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_border_opa(ui_ExitButtonInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ExitButtonInfo, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ExitButtonInfo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_translate_y(ui_ExitButtonInfo, -7, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_ExitButtonLabel = lv_label_create(ui_ExitButtonInfo);
    lv_obj_set_width( ui_ExitButtonLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_ExitButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_ExitButtonLabel, LV_ALIGN_CENTER );
    lv_label_set_text(ui_ExitButtonLabel, "<");
    lv_obj_set_style_text_color(ui_ExitButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_ExitButtonLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ExitButtonLabel, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

    /* add event callback to exit button to change screen to ui_Screen8 */
    lv_obj_add_event_cb(ui_ExitButtonInfo, ui_event_ExitButtonInfo, LV_EVENT_CLICKED, NULL);

    ui_RightBody = lv_obj_create(ui_BodyInfo);
    lv_obj_remove_style_all(ui_RightBody);
    lv_obj_set_width( ui_RightBody, 370);
    lv_obj_set_height( ui_RightBody, lv_pct(97));
    lv_obj_set_x( ui_RightBody, -1 );
    lv_obj_set_y( ui_RightBody, -1 );
    lv_obj_set_align( ui_RightBody, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_RightBody,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_RightBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_RightBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_pad_row(ui_RightBody, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RightBody, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_OfficePanel = lv_obj_create(ui_RightBody);
    lv_obj_set_width( ui_OfficePanel, lv_pct(95));
    lv_obj_set_height( ui_OfficePanel, lv_pct(40));
    lv_obj_set_align( ui_OfficePanel, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_OfficePanel,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_OfficePanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_OfficePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_radius(ui_OfficePanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OfficePanel, lv_color_hex(0x303031), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_OfficePanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OfficePanel, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_border_opa(ui_OfficePanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_OfficePanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_OfficePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OfficePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OfficePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OfficePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_OfficePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_OfficePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_OfficeCont = lv_obj_create(ui_OfficePanel);
    lv_obj_remove_style_all(ui_OfficeCont);
    lv_obj_set_width( ui_OfficeCont, UI_INFO_TEXT_COLUMN_WIDTH);
    lv_obj_set_height( ui_OfficeCont, lv_pct(100));
    lv_obj_set_x( ui_OfficeCont, UI_INFO_TEXT_COLUMN_OFFSET_X );
    lv_obj_set_y( ui_OfficeCont, 0 );
    lv_obj_set_align( ui_OfficeCont, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_OfficeCont,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_OfficeCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag( ui_OfficeCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_HeaderOffice = lv_obj_create(ui_OfficeCont);
    lv_obj_remove_style_all(ui_HeaderOffice);
    lv_obj_set_width( ui_HeaderOffice, lv_pct(100));
    lv_obj_set_height( ui_HeaderOffice, lv_pct(42));
    lv_obj_set_align( ui_HeaderOffice, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_HeaderOffice,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_HeaderOffice, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag( ui_HeaderOffice, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_pad_row(ui_HeaderOffice, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_HeaderOffice, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_HeaderOfficeLabel1 = lv_label_create(ui_HeaderOffice);
    lv_obj_set_width( ui_HeaderOfficeLabel1, lv_pct(100));
    lv_obj_set_height( ui_HeaderOfficeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_HeaderOfficeLabel1, LV_ALIGN_CENTER );
    lv_label_set_long_mode(ui_HeaderOfficeLabel1, LV_LABEL_LONG_WRAP);
    lv_label_set_text(ui_HeaderOfficeLabel1,"Office Map");
    lv_obj_set_style_text_color(ui_HeaderOfficeLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_HeaderOfficeLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaderOfficeLabel1, &ui_font_Roboto26, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HeaderOfficeLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaderOfficeLanel2 = lv_label_create(ui_HeaderOffice);
    lv_obj_set_width( ui_HeaderOfficeLanel2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_HeaderOfficeLanel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_HeaderOfficeLanel2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_HeaderOfficeLanel2,"");
    lv_obj_set_style_text_color(ui_HeaderOfficeLanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_HeaderOfficeLanel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaderOfficeLanel2, &ui_font_Roboto12, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_HeaderOfficeLanel2, LV_OBJ_FLAG_HIDDEN);

    ui_BottonOffice = lv_obj_create(ui_OfficeCont);
    lv_obj_remove_style_all(ui_BottonOffice);
    lv_obj_set_width( ui_BottonOffice, lv_pct(100));
    lv_obj_set_height( ui_BottonOffice, lv_pct(34));
    lv_obj_set_align( ui_BottonOffice, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_BottonOffice,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BottonOffice, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_BottonOffice, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_pad_row(ui_BottonOffice, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_ScanOffice = lv_label_create(ui_BottonOffice);
    lv_obj_set_width( ui_ScanOffice, lv_pct(100));
    lv_obj_set_height( ui_ScanOffice, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_ScanOffice, LV_ALIGN_CENTER );
    lv_label_set_long_mode(ui_ScanOffice, LV_LABEL_LONG_WRAP);
    lv_label_set_text(ui_ScanOffice,"Scan QR\nfor office map");
    lv_obj_set_style_text_color(ui_ScanOffice, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_ScanOffice, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScanOffice, &ui_font_Roboto18, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScanOffice, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfficeImage = lv_obj_create(ui_OfficePanel);
    lv_obj_set_x( ui_OfficeImage, UI_INFO_QR_OFFSET_X );
    lv_obj_set_y( ui_OfficeImage, 0 );
    lv_obj_set_align( ui_OfficeImage, LV_ALIGN_CENTER );
    ui_info_style_qr_frame(ui_OfficeImage);

    /* Meeting room QR section removed intentionally. */

    /* Register language callback so this screen updates if user toggles language elsewhere */
    s_lang_cb_id = language_register_callback(ui_info_lang_cb, NULL);


    /* Apply current language to all labels (initial) */
    ui_info_apply_language(language_get_en());
}

void ui_ScreenInfo_screen_destroy(void)
{
    /* unregister language callback for this screen */
    if (s_lang_cb_id > 0) {
        language_unregister_callback(s_lang_cb_id);
        s_lang_cb_id = -1;
    }


   if (ui_ScreenInfo) lv_obj_del(ui_ScreenInfo);

   // NULL screen variables
   ui_ScreenInfo= NULL;
   ui_HeaderInfo= NULL;
   ui_InfoLabelHeader= NULL;
   ui_BodyInfo= NULL;
   ui_LeftBody= NULL;
   ui_GuestWifi= NULL;
   ui_GuestCont= NULL;
   ui_HeaderGuest= NULL;
   ui_HeaderGuestLabel1= NULL;
   ui_HeaderGuestLabel2= NULL;
   ui_BottomHeader= NULL;
   ui_BottonWifi= NULL;
   ui_BottomPass= NULL;
   ui_GuestImage= NULL;
   ui_CompanyWeb= NULL;
   ui_CompanyCont= NULL;
   ui_HeaderComp= NULL;
   ui_ComanyHeaderLabel1= NULL;
   ui_CompanyHeaderLabel2= NULL;
   ui_BottomComp= NULL;
   ui_ScanComp= NULL;
   ui_CompanyImage= NULL;
   ui_ExitButtonInfo= NULL;
   ui_ExitButtonLabel= NULL;
   ui_RightBody= NULL;
   ui_OfficePanel= NULL;
   ui_OfficeCont= NULL;
   ui_HeaderOffice= NULL;
   ui_HeaderOfficeLabel1= NULL;
   ui_HeaderOfficeLanel2= NULL;
   ui_BottonOffice= NULL;
   ui_ScanOffice= NULL;
   ui_OfficeImage= NULL;
}
